### ISSUE TITLE
Contract: Investigate simplifying fuses.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/PetalLock#64]
https://github.com/DarkFlorist/PetalLock/blob/7a9697593bc929f7902ee81928b975517cd92866/solidity/contracts/PetalLock.sol#L72

If we can burn the same set of fuses for the leaf, regardless of whether or not it is the 2LN or NthLN, then we should even if it is unnecessary.  Burning fuses is essentially free once you burn one (just an INT update), so burning many/all is fine if it is simpler and achieves the same goal.

**Comment by MicahZoltu** [comment]
Since this is the leaf node, I think we *always* will receive ownership of it, so we can safely burn fuses without worrying about the correct fuses being set and the name not being transferred to us?  Or can a user go through this process when a leaf is correctly configured but a parent isn't?

**Comment by KillariDev** [comment]
we cannot have the same fuses for both. The 2ld fuses are set with:
```
ensNameWrapper.setFuses(bytes32 node, uint16 fuses) external returns (uint32);
```
as we control the 2ld and are setting it's own fuses, while with Nlds (where N>2) we control the parent and set the fuses of it via:
```
ensNameWrapper.setSubnodeRecord(bytes32 parentNode, string memory label, address owner, address resolver, uint64 ttl, uint32 fuses, uint64 expiry) external returns(bytes32 node);
```

The important fuses to set for N>2:s are PARENT_CANNOT_CONTROL and CAN_EXTEND_EXPIRY, which we cannot set for 2LDs, but they would not do anything there either.
