### ISSUE TITLE
Contract: Why?

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/PetalLock#65]
https://github.com/DarkFlorist/PetalLock/blob/7a9697593bc929f7902ee81928b975517cd92866/solidity/contracts/PetalLock.sol#L74

Why do you have a constant for this rather than just inlining `type(uint64).max`.  On net it is adding code that could be avoided I think.

**Comment by KillariDev** [comment]
I feel the constant is cleaner than using `type(uint64).max;` everywhere
