### ISSUE TITLE
Contract: Use constant everywhere.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/PetalLock#66]
https://github.com/DarkFlorist/PetalLock/blob/7a9697593bc929f7902ee81928b975517cd92866/solidity/contracts/OpenRenewalManager.sol#L21-L31

Rather than have a constant that is passed from the derived contract (`OpenRenewalManager`) to base contract (`ReverseClaimer`), just move the constant definition to the top of the file and remove the `ReverseClaimer` constructor parameter.

**Comment by MicahZoltu** [comment]
Actually, why is this a base contract at all?  Seems like we could just add 2 lines to the constructor of `OpenRenewalManager` and remove the entire base class.

**Comment by KillariDev** [comment]
> Actually, why is this a base contract at all? Seems like we could just add 2 lines to the constructor of `OpenRenewalManager` and remove the entire base class.

This is how it was done in the original renewal manager, I thought it might be cleaner to do it this way to look more standard

**Comment by MicahZoltu** [comment]
I think we should keep everything in the one contract (class) rather than split it into base and derived.  We aren't benefitting from any code reuse here, and the layer of abstraction addition is slightly confusing.
